
name: Build Image

# Controls when the workflow will run
on:
  push:
    branches-ignore:
      - main
    paths:
      - Dockerfile

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag Name'
        required: false
        default: 'latest'

env:
  LOCAL_IMAGE     : "local-image:${{ github.sha }}"
  NAMESPACE       : "${{ secrets.DOCKER_NAMESPACE }}"
  REPOSITORY_NAME : "${{ github.ref_name }}"
    ## the branch name (`github.ref_name`) of the github repository is the repository name in the container registry
  TAG_NAME        : "${{ github.event.inputs.tag_name || 'latest' }}"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  process:
    if: ${{ github.ref_name != 'main' }}
    # The type of runner that the job will run on
    runs-on: windows-2022

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build Docker Image
        run: |
          docker build --no-cache --tag "%LOCAL_IMAGE%" --file "Dockerfile" .
